### ISSUE TITLE
Double as parameters

### ISSUE THREAD

**Issue by le-roux** [TelecomParistoc/libAX12#4]
Why some parameters are of type "double" (for instance in AX12setSpeed or AX12sgetSpeed) whereas actual values are only integers?

**Comment by superpingu** [comment]
The idea is that it is easier to think in degrees (to measure real movements or theoretical movements in Fusion for example), but I don't wan't to lose any precision. 

With its mighty quad-core Cortex-A53@1.2GHz the raspberry pi does the conversion in a fraction of a ms, so it is not really relevant to optimize. 

Of course this does not apply to other platforms ;)

**Comment by le-roux** [comment]
But you actually lose precision as the double are rounded to integer for communication.
If you think of precision for upper layer computation, I'm not sure that this layer is involved. On the contrary, it lets users think that they have "double" precision whereas the actual precision is only "integer".

**Comment by le-roux** [comment]
Ok, I see the point.  As the AX12 has a precision of more than 1 degree, using int would add an over limitation to precision.
